{% set version = "0.10.4" %}

package:
    name: pyfftw
    version: {{ version }}

source:
    fn: pyFFTW-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/p/pyFFTW/pyFFTW-{{ version }}.tar.gz
    sha256: 739b436b7c0aeddf99a48749380260364d2dc027cf1d5f63dafb5f50068ede1a

build:
  number: 0
  skip: True  # [win]

requirements:
    build:
        - cython
        - python
        - numpy x.x
        - fftw
    run:
        - python
        - numpy x.x

about:
    home: http://hgomersall.github.com/pyFFTW/
    license: BSD or GPL 2
    summary: 'A pythonic wrapper around FFTW, the FFT library, presenting a unified interface for all the supported transforms.'

extra:
    recipe-maintainers:
        - grlee77
        - jakirkham
        - jjhelmus
