{% set name = "pyFFTW" %}
{% set version = "0.13.1" %}
{% set sha256 = "ffc1b3e7f4f74ee38716d668d7606b5fbfded58343655c160c3644fc4acf5d55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-cython3-updates-and-test-build-linker-flags.patch
    - patches/0002-no-system-include.patch

build:
  number: 0
  # fftw not available for s390x
  # versioneer not updated for py312
  skip: true  # [py<38 or py>311 or s390x]
  ignore_run_exports:
    - fftw

requirements:
  build:
    - {{ compiler('c') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - cython >=3
    - python
    - pip
    - setuptools <=59.4.0
    - wheel
    - numpy {{ numpy }}
    - fftw 3.3.9
  run:
    - python
    - {{ pin_compatible('numpy') }}
  run_constrained:
    - dask >=1.0
    - scipy >=1.8.0

{% set tests_to_skip = "" %}
# on arm64 (and aarch64) these tests fail because the platforms
# are not fully tested. See issues (from 2016 and 2021)
#    https://github.com/pyFFTW/pyFFTW/issues/326
#    https://github.com/pyFFTW/pyFFTW/issues/128
{% set tests_to_skip = "test_normalized" %}  
{% set tests_to_skip = tests_to_skip + " or test_flags" %}  # [aarch64 or arm64]
{% set tests_to_skip = tests_to_skip + " or test_aligned_flag" %}  # [aarch64 or arm64]
{% set tests_to_skip = tests_to_skip + " or test_auto_align_input" %}  # [aarch64 or arm64]
{% set tests_to_skip = tests_to_skip + " or test_get_alignment" %}  # [aarch64 or arm64]
{% set tests_to_skip = tests_to_skip + " or test_alignment" %}  # [aarch64 or arm64]

test:
  imports:
    - pyfftw
    - pyfftw.builders
    - pyfftw.interfaces
  requires:
    - pip
    - pytest
    - scipy >=1.2.0
  source_files:
    - tests
  commands:
    - pip check
    - pytest --import-mode=append -k "not ({{ tests_to_skip }})" tests/

about:
  home: https://github.com/pyFFTW/pyFFTW
  license: BSD-3-Clause and BSD-2-Clause and GPL-2.0
  license_file: LICENSE.txt
  license_family: Other
  summary: A pythonic wrapper around FFTW, the FFT library, presenting a unified interface for all the supported transforms.
  description: |
    pyFFTW is a pythonic wrapper around FFTW, the speedy FFT library. The ultimate aim is to present a unified interface for 
    all the possible transforms that FFTW can perform.

    Both the complex DFT and the real DFT are supported, as well as on arbitrary axes of abitrary shaped and strided arrays, 
    which makes it almost feature equivalent to standard and real FFT functions of numpy.fft (indeed, it supports the 
    clongdouble dtype which numpy.fft does not).
  dev_url: https://github.com/pyFFTW/pyFFTW
  doc_url: https://pyfftw.readthedocs.io

extra:
  recipe-maintainers:
    - grlee77
    - hgomersall
    - jakirkham
