{% set name = "pyFFTW" %}
{% set version = "0.13.1" %}
{% set sha256 = "09155e90a0c6d0c1f2d1f3668180a7de95fb9f83fef5137a112fb05978e87320" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-no-system-include.patch
    - patches/0002-restore-linker-flags-when-testing-for-functions.patch

build:
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('c') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - cython
    - python
    - pip
    - setuptools
    - wheel
    - numpy
    - fftw
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://hgomersall.github.com/pyFFTW/
  license: BSD3 and BSD2 and GPL
  license_file: LICENSE.txt
  license_family: Other
  summary: A pythonic wrapper around FFTW, the FFT library, presenting a unified interface for all the supported transforms.
  description: |
    pyFFTW is a pythonic wrapper around FFTW, the speedy FFT library. The ultimate aim is to present a unified interface for 
    all the possible transforms that FFTW can perform.

    Both the complex DFT and the real DFT are supported, as well as on arbitrary axes of abitrary shaped and strided arrays, 
    which makes it almost feature equivalent to standard and real FFT functions of numpy.fft (indeed, it supports the 
    clongdouble dtype which numpy.fft does not).
  dev_url: https://github.com/pyFFTW/pyFFTW
  doc_url: https://pyfftw.readthedocs.io

extra:
  recipe-maintainers:
    - grlee77
    - hgomersall
    - jakirkham
