{% set version = "0.10.2" %}

package:
    name: pyfftw
    version: {{ version }}

source:
    fn: pyFFTW-{{ version }}.tar.gz
    # url: https://pypi.io/packages/source/p/pyFFTW/pyFFTW-{{ version }}.tar.gz
    # md5: 20c0f3bb8153e7a4ab8bcbfe286248e8
    url: https://github.com/pyFFTW/pyFFTW/archive/v10.2.tar.gz
    md5: f44c0eea45daf20a2697f031b4590709

build:
  number: 0
  skip: True  # [win]

requirements:
    build:
        - cython
        - python
        - numpy
        - fftw
    run:
        - python
        - numpy

test:
    imports:
        - pyfftw
        - pyfftw.builders
        - pyfftw.interfaces

about:
    home: http://hgomersall.github.com/pyFFTW/
    license: BSD or GPL 2
    summary: 'A pythonic wrapper around FFTW, the FFT library, presenting a unified interface for all the supported transforms.'

extra:
    recipe-maintainers:
        - grlee77
        - jakirkham
        - jjhelmus
