travis:
  secure:
    BINSTAR_TOKEN: ECHNxH85deGqivoejaLz/RibLF0K1UVJ4XgNjC3uyaWQ9DoN8XihNDHFw6gm+bT6GhpyJEFnJF8TyrQ01fX9cJVBrnTpejpSd6lsrvnada3/vcq5yTIqnplSesZmci2uB0P9JnwBN9ipvQT/32x01CDw+YGIrJCPQkAhGJ5nZ+ZVxs9jwHTnfOi/PbWTlB7ntWWNesfD4eTlhspJrVFxesqSC+cGF26kVrsDB6opyvo3d+MeyMWrkeatuaCiB6Yh5k9o7Kz+r6b2DLdtG6sx4j9bvbN9nfVLykOiOio7+dPM0NduNHu5YAHM5tlkBnymFHgtfAMXNLAV55y/Yg6YLqdpzSmL0lRV4Kr3Ln73j0iywQ/1hjAIDZ/GN7YKTkR8Tc1PkUIONFM7NbxrUk07epLajccjHlwPX43dkA9yqEyYT/9APVkCAT4auOY3324nyod2TRVNtzD7ie5C5X4cshxSyHLpejfUPlug9rSJ1va3xAC0tSwkiNVEs/Kda0Tqd8cGu+2NBW/oNOcp+UIeXboBJloalW5FP+TTRB9rpRUoj4bcagmvgxk3Sq+fneNCJKP8QmZt1wBUmfmVm/nd3rsK6LfuC5VWWFttqjFOdmElnMgfDRNHkeo7YvF+uroUwOTHm30xgE6Xe6KkBWeVBNOZHCfpv82l5UckoUpC5YY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
